#!/bin/bash

# Q Manager
# Uses qsub and qstat to sub a job
#
# Q - prints current jobs in queue
# Q "casname" - subs casname to queue

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


# Interface functions
function sub_job {
    echo -e "${BLUE}Submitting job \"$1\" ${NC}"
    qsub $1
}
function get_queue {
    name=$(whoami)
    short=${name:0:6}
    echo $(qstat -T | grep "$short" )
}
function jobs_in_queue {
    name=${whoami}
    short=${name:0:6}
    out=$( qstat -T | grep "$name|$1" )
    echo "$out"

    if [["$out" = "" ]]; then
        return 1
    else
        return 0
    fi
}

# Manage program flow
cas="$1"

if [[ -z "$cas" ]]; then
    echo -e "${BLUE}Jobs in queue ${NC}"
    echo $(get_queue)
else
    # Argument exists
    sub_job $cas
    echo $(get_queue)
fi
