#!/bin/bash

# Q Manager
# Uses qsub and qstat to sub a job
#
# Q - prints current jobs in queue
# Q "casname" - subs casname to queue

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


# Interface functions
function sub_job {
    echo -e "${BLUE} Submitting job $1 ${NC}"
    qsub $1
}
function get_queue {
    return $(qstat -T | grep "$(whoami)" )
}
function jobs_in_queue {
    out=$(qstat -T | grep "$(whoami)|$1" )

    if ["$out" = "" ]; then
        return true
    else
        return false
    fi
}


# Manage program flow
cas="$1"

if ["$cas" = ""]; then
    if jobs_in_queue $cas; then
        echo "No jobs in queue:"
    else
        echo "Jobs in queue:"
        echo $(get_queue)
    fi

else
    # Argument exists
    sub_job $cas
    echo $(get_queue)
fi
